(() => {
 let anchor=null,data=null;
 const boot=async()=>{
  const api=window.WhenWeMeetUX3456,g=document.querySelector('#availability-grid');if(!api||!g)return;
  g.addEventListener('click',e=>{const c=e.target.closest('.slot-cell');if(!c||c.disabled)return;if(e.shiftKey&&anchor){e.preventDefault();api.fillRange(anchor,c);anchor=null;toast('Range filled.');}else anchor=c;},true);
  const results=document.querySelector('#results-grid');const recolor=()=>results?.querySelectorAll('.slot-cell').forEach(c=>{const m=c.textContent.match(/(\d+)\/(\d+)/);if(m){const r=+m[2]?+m[1]/+m[2]:0;c.style.background=api.heatColor(r);c.style.color=r>.58?'#081b12':'';}});if(results){new MutationObserver(recolor).observe(results,{childList:true,subtree:true});recolor();}
  try{data=await fetch('./schedule-data.json?v=20260924e',{cache:'no-store'}).then(r=>r.json());const form=document.querySelector('#join-form'),wrap=document.createElement('div');wrap.className='locked-presets';wrap.innerHTML='<strong>Quick fill from locked schedule</strong><div class="locked-preset-buttons"></div>';data.people.forEach(p=>{const b=document.createElement('button');b.type='button';b.className='button ghost compact';b.textContent=p;b.onclick=()=>api.applyLockedPreset(p);wrap.lastElementChild.append(b);});form?.insertAdjacentElement('afterend',wrap);}catch(e){console.warn(e)}
  const share=document.querySelector('#share-button');if(share){const tools=document.createElement('div');tools.className='share-extra';const qr=document.createElement('button');qr.type='button';qr.className='button ghost compact';qr.textContent='QR';const code=document.createElement('span');code.className='room-code';code.textContent=api.roomCode();tools.append(qr,code);share.parentElement.append(tools);qr.onclick=()=>{const url=location.href,w=window.open('','WhenWeMeetQR','width=360,height=440');if(!w)return;const img='https://api.qrserver.com/v1/create-qr-code/?size=260x260&data='+encodeURIComponent(url);w.document.write('<title>Scan to join</title><body style="font-family:system-ui;text-align:center;padding:24px"><h2>Scan to join</h2><img width="260" height="260" src="'+img+'"><p>'+code.textContent+'</p></body>');};}
  const s=document.createElement('style');s.textContent='.locked-presets{margin-top:12px;padding:12px;border:1px solid var(--line);border-radius:14px;background:var(--surface-muted)}.locked-presets strong{display:block;font-size:.78rem;margin-bottom:8px}.locked-preset-buttons{display:flex;gap:7px;flex-wrap:wrap}.share-extra{display:flex;align-items:center;gap:8px}.room-code{font:800 .72rem ui-monospace,monospace;letter-spacing:.06em;color:var(--muted)}';document.head.append(s);
 };
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,100));else setTimeout(boot,100);
})();