(() => {
  "use strict";
  const SNAPSHOT_URL="https://cdn.jsdelivr.net/gh/unitedstates/congress-legislators@73e2fcd181e1c48d1b0580d417e8d0314b22f7c9/legislators-current.json";
  const LIVE_SQL="SELECT bioguide_id, full_name, party, state, chamber, district, birthday FROM congress_members WHERE is_current=1 ORDER BY full_name LIMIT 1000";
  const LIVE_URL="https://regs.datadawn.org/openregs.json?sql="+encodeURIComponent(LIVE_SQL)+"&_shape=objects";
  const FEC_API="https://api.open.fec.gov/v1";
  const FEC_KEY="DEMO_KEY";
  const NONVOTING=new Set(["AS","DC","GU","MP","PR","VI"]);
  const REGION={CT:"Northeast",ME:"Northeast",MA:"Northeast",NH:"Northeast",RI:"Northeast",VT:"Northeast",NJ:"Northeast",NY:"Northeast",PA:"Northeast",IL:"Midwest",IN:"Midwest",MI:"Midwest",OH:"Midwest",WI:"Midwest",IA:"Midwest",KS:"Midwest",MN:"Midwest",MO:"Midwest",NE:"Midwest",ND:"Midwest",SD:"Midwest",DE:"South",FL:"South",GA:"South",MD:"South",NC:"South",SC:"South",VA:"South",DC:"South",WV:"South",AL:"South",KY:"South",MS:"South",TN:"South",AR:"South",LA:"South",OK:"South",TX:"South",AZ:"West",CO:"West",ID:"West",MT:"West",NV:"West",NM:"West",UT:"West",WY:"West",AK:"West",CA:"West",HI:"West",OR:"West",WA:"West",AS:"Territory",GU:"Territory",MP:"Territory",PR:"Territory",VI:"Territory"};
  const GENERIC_EMPLOYERS=/^(NOT EMPLOYED|NONE|SELF|SELF-EMPLOYED|RETIRED|N\/A|NA|INFORMATION REQUESTED|REQUESTED|HOMEMAKER|UNEMPLOYED|NOT APPLICABLE|UNKNOWN)$/i;
  const COLORS={blue:"#4f8dff",red:"#ff5c65",green:"#57e69d",yellow:"#e6ff62",purple:"#b77cff",cyan:"#59c7ff",orange:"#ffb15a",gray:"#657083"};
  const charts=[];

  const $=id=>document.getElementById(id);
  function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
  function money(v){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n):"Not reported";}
  function compactMoney(v){const n=Number(v);if(!Number.isFinite(n))return"-";return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1}).format(n);}
  function pct(v){const n=Number(v);return Number.isFinite(n)?`${n.toFixed(1)}%`:"-";}
  function num(row,...keys){for(const k of keys){const n=Number(row?.[k]);if(Number.isFinite(n))return n;}return 0;}
  function age(b){if(!b)return null;const p=String(b).slice(0,10).split("-").map(Number),d=new Date();let a=d.getFullYear()-p[0];if(p[1]>d.getMonth()+1||(p[1]===d.getMonth()+1&&p[2]>d.getDate()))a--;return a;}
  function niceDate(iso){if(!iso)return"Unknown";const[y,m,d]=String(iso).slice(0,10).split("-").map(Number);if(!y||!m||!d)return iso;return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(y,m-1,d)));}
  function cycleNow(){const y=new Date().getFullYear();return y%2===0?y:y+1;}
  function serviceStartCycle(m){const y=m.firstServiceYear||cycleNow();return y%2===0?y:y-1;}
  function seat(m){if(m.chamber==="Senate")return`${m.state} senator`;if(m.nonvoting)return`${m.state} nonvoting House member`;return`${m.state} ${m.district===0?"at-large":`district ${m.district}`}`;}
  function region(m){return REGION[m.state]||"Unknown";}
  function officeFecId(m){const prefix=m.chamber==="Senate"?"S":"H";const ids=(m.fecIds||[]).filter(x=>String(x).startsWith(prefix));return ids.at(-1)||(m.fecIds||[])[0]||"";}
  function yearsServed(m){return m.firstServiceYear?Math.max(0,new Date().getFullYear()-m.firstServiceYear):null;}
  function queryId(){return new URLSearchParams(location.search).get("id")||location.hash.replace(/^#member=/,"")||"";}
  async function json(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`Request failed (${r.status})`);return await r.json();}finally{clearTimeout(t);}}
  function fecUrl(path,params={}){const u=new URL(FEC_API+path);u.searchParams.set("api_key",FEC_KEY);for(const[k,v]of Object.entries(params)){if(Array.isArray(v))v.forEach(x=>u.searchParams.append(k,x));else if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,v);}return u.toString();}

  function normalizeSnapshot(x,i){const terms=Array.isArray(x.terms)?x.terms:[],t=terms.at(-1)||{},n=x.name||{},b=x.bio?.birthday||"",raw=x.id?.fec,fec=Array.isArray(raw)?raw:(raw?[raw]:[]),first=terms.find(v=>v?.start)||terms[0]||{};return{id:x.id?.bioguide||`snapshot-${i}`,name:n.official_full||[n.first,n.middle,n.last,n.suffix].filter(Boolean).join(" "),party:t.party||"Independent",state:t.state||"",chamber:t.type==="sen"?"Senate":"House",district:t.type==="sen"?null:(t.district??null),birthday:b,age:age(b),nonvoting:t.type==="rep"&&NONVOTING.has(t.state||""),fecIds:fec,opensecrets:x.id?.opensecrets||"",website:t.url||"",phone:t.phone||"",senateClass:t.class||null,firstServiceYear:Number(String(first.start||"").slice(0,4))||null,termCount:terms.length};}

  async function loadRoster(){const [snapResult,liveResult]=await Promise.allSettled([fetch(SNAPSHOT_URL,{cache:"force-cache"}).then(r=>r.ok?r.json():[]),fetch(LIVE_URL,{cache:"no-store"}).then(r=>r.ok?r.json():[])]);const snap=snapResult.status==="fulfilled"?snapResult.value:[],base=snap.map(normalizeSnapshot),map=new Map(base.map(m=>[m.id,m]));const rawLive=liveResult.status==="fulfilled"?liveResult.value:[],live=Array.isArray(rawLive)?rawLive:(rawLive.rows||[]);if(live.length>500){for(const r of live){const b=map.get(r.bioguide_id)||{};map.set(r.bioguide_id,{...b,id:r.bioguide_id,name:r.full_name||b.name||"Unknown",party:r.party||b.party||"Independent",state:r.state||b.state||"",chamber:r.chamber==="Senate"?"Senate":"House",district:r.chamber==="Senate"?null:(r.district??b.district??null),birthday:r.birthday||b.birthday||"",age:age(r.birthday||b.birthday||""),nonvoting:r.chamber==="House"&&NONVOTING.has(r.state||b.state||"")});}}return[...map.values()];}

  async function totals(id){const j=await json(fecUrl(`/candidate/${encodeURIComponent(id)}/totals/`,{per_page:100,sort:"-cycle",election_full:"false"}));return(j.results||[]).map(r=>({...r,_candidateId:id}));}
  function collapse(rows){const g=new Map();for(const r of rows){const c=Number(r.cycle);if(!c)continue;const k=`${r._candidateId}|${c}`,old=g.get(k);if(!old||num(r,"receipts","total_receipts")>num(old,"receipts","total_receipts"))g.set(k,r);}return[...g.values()];}
  function aggregateCycles(rows){const g=new Map();for(const r of rows){const c=Number(r.cycle);if(!c)continue;const v=g.get(c)||{cycle:c,receipts:0,spent:0,individual:0,pac:0,candidate:0,party:0,cash:0,debt:0,coverageEnd:""};v.receipts+=num(r,"receipts","total_receipts");v.spent+=num(r,"disbursements","total_disbursements");v.individual+=num(r,"individual_contributions");v.pac+=num(r,"other_political_committee_contributions","other_political_committee_contributions_period");v.candidate+=num(r,"candidate_contribution","candidate_contributions");v.party+=num(r,"political_party_committee_contributions");v.cash+=num(r,"cash_on_hand_end_period");v.debt+=num(r,"debts_owed_by_committee");if(r.coverage_end_date>v.coverageEnd)v.coverageEnd=r.coverage_end_date;g.set(c,v);}return[...g.values()].sort((a,b)=>a.cycle-b.cycle);}
  function committeeIds(row){return[...new Set([row?.committee_id,...(Array.isArray(row?.committee_ids)?row.committee_ids:[])].filter(Boolean))];}
  async function employers(ids,cycle){if(!ids.length)return[];const j=await json(fecUrl("/schedules/schedule_a/by_employer/",{committee_id:ids,cycle,per_page:30,sort:"-total"}));return(j.results||[]).map(r=>({name:String(r.employer||"").trim(),amount:num(r,"total"),count:num(r,"count")})).filter(r=>r.name&&!GENERIC_EMPLOYERS.test(r.name)&&r.amount>0).slice(0,12);}
  async function pacs(ids,cycle){if(!ids.length)return[];const j=await json(fecUrl("/schedules/schedule_a/",{committee_id:ids,two_year_transaction_period:cycle,line_number:"F3-11C",per_page:100,sort:"-contribution_receipt_amount"}));const g=new Map();for(const r of j.results||[]){const a=num(r,"contribution_receipt_amount"),n=String(r.contributor_name||"").trim();if(!n||a<=0||r.memoed_subtotal===true)continue;const k=n.toUpperCase(),v=g.get(k)||{name:n,amount:0,count:0};v.amount+=a;v.count++;g.set(k,v);}return[...g.values()].sort((a,b)=>b.amount-a.amount).slice(0,12);}

  async function loadFinance(m){const ids=(m.fecIds||[]).filter(Boolean);if(!ids.length)throw new Error("No FEC candidate ID is listed for this member.");const sets=await Promise.all(ids.map(id=>totals(id).catch(()=>[]))),collapsed=collapse(sets.flat());if(!collapsed.length)throw new Error("The FEC returned no candidate totals for this member.");const cycles=aggregateCycles(collapsed),officeId=officeFecId(m),officeRows=collapsed.filter(r=>r._candidateId===officeId&&Number(r.cycle)<=cycleNow()).sort((a,b)=>Number(b.cycle)-Number(a.cycle)||num(b,"receipts")-num(a,"receipts")),latestRow=officeRows[0]||collapsed.sort((a,b)=>Number(b.cycle)-Number(a.cycle))[0],latestCycle=Number(latestRow.cycle)||cycleNow(),startCycle=serviceStartCycle(m),serviceCycles=cycles.filter(c=>c.cycle>=startCycle&&c.cycle<=cycleNow()),latestAgg=cycles.find(c=>c.cycle===latestCycle)||serviceCycles.at(-1)||cycles.at(-1),cids=committeeIds(latestRow),[emps,pcs]=await Promise.all([employers(cids,latestCycle).catch(()=>[]),pacs(cids,latestCycle).catch(()=>[])]);return{ids,officeId,latestRow,latestCycle,latestAgg,cycles,serviceCycles,employers:emps,pacs:pcs};}

  function renderHero(m){document.title=`${m.name} | Old Ass Politic`;$('memberName'.replace("'","")).textContent=m.name;$("memberSub").textContent=`${m.party} · ${seat(m)} · age ${m.age}`;$("memberPills").innerHTML=[m.party,m.chamber,region(m),m.nonvoting?"Nonvoting":"Voting member"].map(x=>`<span class="pill">${esc(x)}</span>`).join("");}
  function ageStats(m,roster){const chamber=roster.filter(x=>x.chamber===m.chamber&&Number.isFinite(x.age)).sort((a,b)=>b.age-a.age),all=roster.filter(x=>Number.isFinite(x.age)),rank=chamber.findIndex(x=>x.id===m.id)+1,chAvg=chamber.reduce((s,x)=>s+x.age,0)/Math.max(chamber.length,1),allAvg=all.reduce((s,x)=>s+x.age,0)/Math.max(all.length,1);return{rank,total:chamber.length,chAvg,allAvg};}
  function sum(rows,key){return rows.reduce((s,r)=>s+(r[key]||0),0);}

  function renderStats(m,f,a){const sc=f.serviceCycles,latest=f.latestAgg,careerReceipts=sum(sc,"receipts"),careerSpent=sum(sc,"spent"),yrs=yearsServed(m);$("statRaised").textContent=compactMoney(latest.receipts);$("statRaisedCycle").textContent=`${f.latestCycle} election cycle`;$("statSpent").textContent=compactMoney(latest.spent);$("statCash").textContent=compactMoney(latest.cash);$("statCareer").textContent=compactMoney(careerReceipts);$("statCareerCycles").textContent=`${sc.length} FEC cycle${sc.length===1?"":"s"} covered`;$("statAgeRank").textContent=a.rank?`#${a.rank} / ${a.total}`:"-";$("statAgeRankSub").textContent=`Oldest rank in ${m.chamber}`;$("statYears").textContent=yrs===null?"-":yrs.toLocaleString();$("statSince").textContent=m.firstServiceYear?`Listed since ${m.firstServiceYear}`:"First term unknown";
    const avgR=sc.length?careerReceipts/sc.length:0,avgS=sc.length?careerSpent/sc.length:0,ratio=careerReceipts?careerSpent/careerReceipts*100:0,latestRatio=latest.receipts?latest.spent/latest.receipts*100:0,net=careerReceipts-careerSpent,employerTotal=sum(f.employers,"amount"),pacTotal=sum(f.pacs,"amount"),topEmp=f.employers[0]?.amount||0;
    const rows=[
      ["Service-era spending",money(careerSpent),`${sc.length} cycles summed`],["Receipts minus spending",money(net),"Not profit; simple cash-flow comparison"],["Average receipts / cycle",money(avgR),"Service-era mean"],["Average spending / cycle",money(avgS),"Service-era mean"],["Career spend / receipts",pct(ratio),"Disbursements divided by receipts"],[`${f.latestCycle} spend / receipts`,pct(latestRatio),"Latest cycle ratio"],["Latest individual contributions",money(latest.individual),"FEC total field"],["Latest PAC / committee total",money(latest.pac),"FEC total field"],["Displayed employer sample",money(employerTotal),`${f.employers.length} employer groups shown`],["Top employer share",employerTotal?pct(topEmp/employerTotal*100):"-","Of displayed employer sample"],["Displayed PAC transactions",money(pacTotal),`${f.pacs.length} PAC / committee groups shown`],["Committee debt",money(latest.debt),"Latest cycle total"]
    ];$("detailStats").innerHTML=rows.map(([l,v,s])=>`<div class="detail-stat"><span>${esc(l)}</span><strong>${esc(v)}</strong><small>${esc(s)}</small></div>`).join("");}

  function renderComparison(m,a){const maxAge=100,yrs=yearsServed(m)||0,maxYears=50;const items=[[`${m.name} age`,m.age,maxAge,`${m.age}`],[`${m.chamber} average`,a.chAvg,maxAge,a.chAvg.toFixed(1)],["Congress average",a.allAvg,maxAge,a.allAvg.toFixed(1)],["Years in Congress",yrs,maxYears,`${yrs}`]];$("comparison").innerHTML=items.map(([label,val,max,text])=>`<div class="compare-row"><label>${esc(label)}</label><div class="track"><div class="fill" style="width:${Math.max(2,Math.min(100,val/max*100))}%"></div></div><strong>${esc(text)}</strong></div>`).join("");}

  function chartDefaults(){if(!window.Chart)return;Chart.defaults.color="#909bad";Chart.defaults.borderColor="rgba(255,255,255,.08)";Chart.defaults.font.family="Manrope, system-ui, sans-serif";}
  function mkChart(el,config){if(!window.Chart)return null;const c=new Chart(el,config);charts.push(c);return c;}
  function renderCharts(f){chartDefaults();const c=f.serviceCycles;mkChart($("cycleChart"),{type:"bar",data:{labels:c.map(x=>String(x.cycle)),datasets:[{label:"Receipts",data:c.map(x=>x.receipts),backgroundColor:COLORS.blue,borderRadius:5},{label:"Spending",data:c.map(x=>x.spent),backgroundColor:COLORS.red,borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{position:"bottom",labels:{boxWidth:9,usePointStyle:true}},tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${money(ctx.raw)}`}}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,ticks:{callback:v=>compactMoney(v)}}}}});
    const l=f.latestAgg,known=l.individual+l.pac+l.candidate+l.party,other=Math.max(0,l.receipts-known),mix=[{n:"Individuals",v:l.individual,c:COLORS.blue},{n:"PAC / committees",v:l.pac,c:COLORS.red},{n:"Candidate self",v:l.candidate,c:COLORS.yellow},{n:"Party committees",v:l.party,c:COLORS.purple},{n:"Other receipts",v:other,c:COLORS.gray}].filter(x=>x.v>0);mkChart($("mixChart"),{type:"doughnut",data:{labels:mix.map(x=>x.n),datasets:[{data:mix.map(x=>x.v),backgroundColor:mix.map(x=>x.c),borderColor:"#111725",borderWidth:3}]},options:{responsive:true,maintainAspectRatio:false,cutout:"68%",plugins:{legend:{display:false},tooltip:{callbacks:{label:ctx=>`${ctx.label}: ${money(ctx.raw)} (${pct(ctx.raw/l.receipts*100)})`}}}}});$("mixLegend").innerHTML=mix.map(x=>`<span><i style="background:${x.c}"></i>${esc(x.n)} ${pct(x.v/l.receipts*100)}</span>`).join("");
    const em=f.employers.slice(0,8);if(em.length)mkChart($("employerChart"),{type:"bar",data:{labels:em.map(x=>x.name),datasets:[{label:"Itemized contributions",data:em.map(x=>x.amount),backgroundColor:COLORS.cyan,borderRadius:5}]},options:{indexAxis:"y",responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:ctx=>money(ctx.raw)}}},scales:{x:{beginAtZero:true,ticks:{callback:v=>compactMoney(v)}},y:{grid:{display:false},ticks:{autoSkip:false,font:{size:9}}}}}});else $("employerChart").parentElement.innerHTML='<div class="empty">No employer-grouped contribution data was returned for this cycle.</div>';}

  function rankList(items,type){if(!items.length)return'<div class="empty">No qualifying records were returned for this cycle, or the public API was rate limited.</div>';const max=Math.max(...items.map(x=>x.amount),1);return items.map((x,i)=>`<div class="rank-row"><div class="rank-fill" style="width:${Math.max(3,x.amount/max*100)}%"></div><div class="rank-content"><div><strong>${i+1}. ${esc(x.name)}</strong><span>${x.count?`${x.count.toLocaleString()} disclosed contribution${x.count===1?"":"s"}`:esc(type)}</span></div><strong>${money(x.amount)}</strong></div></div>`).join("");}
  function renderLists(f,m){$("employerList").innerHTML=rankList(f.employers,"employer grouping");$("pacList").innerHTML=rankList(f.pacs,"PAC / committee");const links=f.employers.slice(0,8).map(x=>{const u=new URL("https://lda.gov/filings/public/filing/search/");u.searchParams.set("client",x.name);if(m.firstServiceYear)u.searchParams.set("report_dt_posted_from",`01/01/${m.firstServiceYear}`);u.searchParams.set("search","search");return`<div class="lobby-row"><strong>${esc(x.name)}</strong><a href="${esc(u.toString())}" target="_blank" rel="noreferrer">Search LDA ↗</a></div>`;});$("lobbyingLinks").innerHTML=links.join("")||'<div class="empty">No employer-based LDA lookup links are available for the latest cycle.</div>';}

  function renderTable(f){const rows=f.serviceCycles.slice().reverse();$("cycleRows").innerHTML=rows.map(r=>`<tr><td><strong>${r.cycle}</strong>${r.coverageEnd?`<br><span style="color:#657083">to ${esc(niceDate(r.coverageEnd))}</span>`:""}</td><td>${money(r.receipts)}</td><td>${money(r.spent)}</td><td>${money(r.individual)}</td><td>${money(r.pac)}</td><td>${money(r.cash)}</td><td>${money(r.debt)}</td><td>${r.receipts?pct(r.spent/r.receipts*100):"-"}</td></tr>`).join("")||'<tr><td colspan="8">No service-era FEC cycles available.</td></tr>';}
  function renderDetails(m,f){const yrs=yearsServed(m),items=[["Current seat",seat(m)],["Party",m.party],["Birthday",`${niceDate(m.birthday)} · age ${m.age}`],["Region",region(m)],["In Congress since",m.firstServiceYear||"Unknown"],["Approx. years served",yrs===null?"Unknown":yrs],["Roster terms",m.termCount||"Unknown"],[m.chamber==="Senate"?"Senate class":"Voting status",m.chamber==="Senate"?(m.senateClass||"Unknown"):(m.nonvoting?"Nonvoting member":"Voting member")],["Office phone",m.phone||"Not listed"],["Bioguide ID",m.id],["FEC candidate IDs",(m.fecIds||[]).join(", ")||"Not listed"],["Current finance cycle",f.latestCycle]];$("memberDetails").innerHTML=items.map(([l,v])=>`<div class="info-item"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`).join("");const sources=[];if(m.website)sources.push(["Official congressional site",m.website]);if(f.officeId)sources.push(["FEC candidate profile",`https://www.fec.gov/data/candidate/${encodeURIComponent(f.officeId)}/?cycle=${f.latestCycle}`]);if(m.opensecrets)sources.push(["OpenSecrets career profile",`https://www.opensecrets.org/members-of-congress/summary?cid=${encodeURIComponent(m.opensecrets)}&cycle=CAREER`]);sources.push(["Congressional Bioguide",`https://bioguide.congress.gov/search/bio/${encodeURIComponent(m.id)}`]);sources.push(["Federal LDA database","https://lda.gov/filings/public/filing/search/"]);$("sourceLinks").innerHTML=sources.map(([n,u])=>`<a class="source-link" href="${esc(u)}" target="_blank" rel="noreferrer">${esc(n)} ↗</a>`).join("");}

  function setStatus(title,sub){$("dataStatus").textContent=title;$("dataStatusSub").textContent=sub;}
  function showError(e){$("errorPanel").hidden=false;$("errorText").textContent=e?.message||String(e);setStatus("Load failed","See error below");}

  async function init(){const id=decodeURIComponent(queryId());if(!id)throw new Error("No member ID was provided. Open a member from the chamber map first.");setStatus("Loading roster","Congressional data");const roster=await loadRoster(),m=roster.find(x=>x.id===id);if(!m)throw new Error(`Member ${id} was not found in the current congressional roster.`);renderHero(m);const a=ageStats(m,roster);setStatus("Loading finance","Federal Election Commission");const f=await loadFinance(m);renderStats(m,f,a);renderComparison(m,a);renderCharts(f);renderLists(f,m);renderTable(f);renderDetails(m,f);setStatus("Live data loaded",`FEC cycle ${f.latestCycle} · current roster`);$("copyLink").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(location.href);$("copyLink").textContent="Copied";setTimeout(()=>$("copyLink").textContent="Copy profile link",1200);}catch{$("copyLink").textContent="Copy failed";}});}
  init().catch(showError);
})();
