(()=>{
  "use strict";
  const SNAPSHOT_URL="https://cdn.jsdelivr.net/gh/unitedstates/congress-legislators@577ca04282d14688cb14f6559eb27b52bdc50dfc/legislators-current.json";
  const FEC_API="https://api.open.fec.gov/v1";
  const FEC_KEY="DEMO_KEY";
  const NONVOTING=new Set(["AS","DC","GU","MP","PR","VI"]);
  const REGION={CT:"Northeast",ME:"Northeast",MA:"Northeast",NH:"Northeast",RI:"Northeast",VT:"Northeast",NJ:"Northeast",NY:"Northeast",PA:"Northeast",IL:"Midwest",IN:"Midwest",MI:"Midwest",OH:"Midwest",WI:"Midwest",IA:"Midwest",KS:"Midwest",MN:"Midwest",MO:"Midwest",NE:"Midwest",ND:"Midwest",SD:"Midwest",DE:"South",FL:"South",GA:"South",MD:"South",NC:"South",SC:"South",VA:"South",DC:"South",WV:"South",AL:"South",KY:"South",MS:"South",TN:"South",AR:"South",LA:"South",OK:"South",TX:"South",AZ:"West",CO:"West",ID:"West",MT:"West",NV:"West",NM:"West",UT:"West",WY:"West",AK:"West",CA:"West",HI:"West",OR:"West",WA:"West",AS:"Territory",GU:"Territory",MP:"Territory",PR:"Territory",VI:"Territory"};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const money=v=>Number.isFinite(Number(v))?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(v)):"-";
  const num=(row,...keys)=>{for(const k of keys){const n=Number(row?.[k]);if(Number.isFinite(n))return n;}return 0};
  function age(b){if(!b)return null;const[y,m,d]=String(b).slice(0,10).split("-").map(Number),n=new Date();let a=n.getFullYear()-y;if(m>n.getMonth()+1||(m===n.getMonth()+1&&d>n.getDate()))a--;return a}
  function niceDate(v){if(!v)return"Unknown";const[y,m,d]=String(v).slice(0,10).split("-").map(Number);return y&&m&&d?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(y,m-1,d))):String(v)}
  function region(m){return REGION[m.state]||"Unknown"}
  function seat(m){if(m.chamber==="Senate")return`${m.state} senator`;if(m.nonvoting)return`${m.state} nonvoting House member`;return`${m.state} ${m.district===0?"at-large":`district ${m.district}`}`}
  function cycleNow(){const y=new Date().getFullYear();return y%2===0?y:y+1}
  function queryId(){return decodeURIComponent(new URLSearchParams(location.search).get("id")||location.hash.replace(/^#member=/,"")||"")}
  function normalize(x,i){const terms=Array.isArray(x.terms)?x.terms:[],t=terms.at(-1)||{},n=x.name||{},b=x.bio?.birthday||"",raw=x.id?.fec,fec=Array.isArray(raw)?raw:(raw?[raw]:[]),first=terms[0]||{};return{id:x.id?.bioguide||`m-${i}`,name:n.official_full||[n.first,n.middle,n.last,n.suffix].filter(Boolean).join(" "),party:t.party||"Independent",state:t.state||"",chamber:t.type==="sen"?"Senate":"House",district:t.type==="sen"?null:(t.district??null),birthday:b,age:age(b),nonvoting:t.type==="rep"&&NONVOTING.has(t.state||""),fecIds:fec,opensecrets:x.id?.opensecrets||"",website:t.url||"",phone:t.phone||"",office:t.office||"",address:t.address||"",contact:t.contact_form||"",senateClass:t.class||null,firstServiceYear:Number(String(first.start||"").slice(0,4))||null,termCount:terms.length}}
  function status(title,sub){$("dataStatus").textContent=title;$("dataStatusSub").textContent=sub}
  function showFatal(msg){$("errorPanel").hidden=false;$("errorText").textContent=msg;status("Profile unavailable","Roster load failed")}
  function renderHero(m){document.title=`${m.name} | Old Ass Politic`;$("memberName").textContent=m.name;$("memberSub").textContent=`${m.party} · ${seat(m)} · age ${m.age}`;$("memberPills").innerHTML=[m.party,m.chamber,region(m),m.nonvoting?"Nonvoting":"Voting member"].map(x=>`<span class="pill">${esc(x)}</span>`).join("")}
  function renderStatic(m,roster){const chamber=roster.filter(x=>x.chamber===m.chamber&&Number.isFinite(x.age)).sort((a,b)=>b.age-a.age),rank=chamber.findIndex(x=>x.id===m.id)+1,yrs=m.firstServiceYear?Math.max(0,new Date().getFullYear()-m.firstServiceYear):null;$("statAgeRank").textContent=rank?`#${rank} / ${chamber.length}`:"-";$("statAgeRankSub").textContent=`Oldest rank in ${m.chamber}`;$("statYears").textContent=yrs??"-";$("statSince").textContent=m.firstServiceYear?`Listed since ${m.firstServiceYear}`:"First term unknown";
    const info=[["Current seat",seat(m)],["Party",m.party],["Birthday",`${niceDate(m.birthday)} · age ${m.age}`],["Region",region(m)],["In Congress since",m.firstServiceYear||"Unknown"],["Roster terms",m.termCount||"Unknown"],[m.chamber==="Senate"?"Senate class":"Voting status",m.chamber==="Senate"?(m.senateClass||"Unknown"):(m.nonvoting?"Nonvoting member":"Voting member")],["Office",m.office||"Not listed"],["Office phone",m.phone||"Not listed"],["Bioguide ID",m.id],["FEC candidate IDs",m.fecIds.length?m.fecIds.join(", "):"Not listed"],["Roster snapshot","September 24, 2026"]];$("memberDetails").innerHTML=info.map(([l,v])=>`<div class="info-item"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`).join("");
    const avg=chamber.reduce((s,x)=>s+x.age,0)/Math.max(1,chamber.length);$("comparison").innerHTML=`<div class="info-grid"><div class="info-item"><span>Member age</span><strong>${m.age}</strong></div><div class="info-item"><span>${esc(m.chamber)} average age</span><strong>${avg.toFixed(1)}</strong></div><div class="info-item"><span>Age difference</span><strong>${m.age>=avg?"+":""}${(m.age-avg).toFixed(1)}</strong></div><div class="info-item"><span>Age rank</span><strong>${rank?`#${rank} of ${chamber.length}`:"Unknown"}</strong></div></div>`;
    const sources=[];if(m.website)sources.push(["Official congressional site",m.website]);sources.push(["Congressional Bioguide",`https://bioguide.congress.gov/search/bio/${encodeURIComponent(m.id)}`]);if(m.opensecrets)sources.push(["OpenSecrets career profile",`https://www.opensecrets.org/members-of-congress/summary?cid=${encodeURIComponent(m.opensecrets)}&cycle=CAREER`]);$("sourceLinks").innerHTML=sources.map(([n,u])=>`<a class="source-link" href="${esc(u)}" target="_blank" rel="noreferrer">${esc(n)} ↗</a>`).join("");
    $("lobbyingLinks").innerHTML=`<a class="source-link" href="https://lda.gov/filings/public/filing/search/" target="_blank" rel="noreferrer">Search federal LDA filings ↗</a>`;
  }
  function financePlaceholder(message){$("statRaised").textContent="-";$("statSpent").textContent="-";$("statCash").textContent="-";$("statCareer").textContent="-";$("statRaisedCycle").textContent="FEC unavailable";$("statCareerCycles").textContent="Profile data still available";$("detailStats").innerHTML=`<div class="notice">${esc(message)}</div>`;$("employerList").innerHTML=`<div class="notice">No finance grouping loaded.</div>`;$("pacList").innerHTML=`<div class="notice">No finance grouping loaded.</div>`;$("cycleRows").innerHTML=`<tr><td colspan="8">Finance data could not be loaded. Congressional profile data above is unaffected.</td></tr>`}
  async function json(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`FEC request failed (${r.status})`);return await r.json()}finally{clearTimeout(t)}}
  function fecUrl(path,params={}){const u=new URL(FEC_API+path);u.searchParams.set("api_key",FEC_KEY);Object.entries(params).forEach(([k,v])=>v!==undefined&&v!==null&&v!==""&&u.searchParams.set(k,v));return u.toString()}
  async function loadFinance(m){if(!m.fecIds.length)throw new Error("No FEC candidate ID is listed for this member.");const all=[];for(const id of m.fecIds){try{const j=await json(fecUrl(`/candidate/${encodeURIComponent(id)}/totals/`,{per_page:100,sort:"-cycle",election_full:"false"}));for(const r of j.results||[])all.push({...r,_candidateId:id})}catch{}}
    if(!all.length)throw new Error("The FEC API returned no totals or is rate limited.");const byCycle=new Map();for(const r of all){const c=Number(r.cycle);if(!c)continue;const cur=byCycle.get(c)||{cycle:c,receipts:0,spent:0,individual:0,pac:0,cash:0,debt:0};cur.receipts+=num(r,"receipts","total_receipts");cur.spent+=num(r,"disbursements","total_disbursements");cur.individual+=num(r,"individual_contributions");cur.pac+=num(r,"other_political_committee_contributions");cur.cash+=num(r,"cash_on_hand_end_period");cur.debt+=num(r,"debts_owed_by_committee");byCycle.set(c,cur)}const cycles=[...byCycle.values()].sort((a,b)=>a.cycle-b.cycle),latest=cycles.filter(x=>x.cycle<=cycleNow()).at(-1)||cycles.at(-1);return{cycles,latest}}
  function renderFinance(m,f){const {cycles,latest}=f,career=cycles.filter(c=>!m.firstServiceYear||c.cycle>=m.firstServiceYear-1),careerReceipts=career.reduce((s,x)=>s+x.receipts,0);$("statRaised").textContent=money(latest.receipts);$("statRaisedCycle").textContent=`${latest.cycle} election cycle`;$("statSpent").textContent=money(latest.spent);$("statCash").textContent=money(latest.cash);$("statCareer").textContent=money(careerReceipts);$("statCareerCycles").textContent=`${career.length} FEC cycle${career.length===1?"":"s"} covered`;
    const ratio=latest.receipts?latest.spent/latest.receipts*100:0;$("detailStats").innerHTML=[["Latest receipts",money(latest.receipts)],["Latest spending",money(latest.spent)],["Latest individual contributions",money(latest.individual)],["Latest PAC / committee total",money(latest.pac)],["Latest cash on hand",money(latest.cash)],["Latest committee debt",money(latest.debt)],["Spend / receipts",`${ratio.toFixed(1)}%`],["Cycles returned",cycles.length]].map(([l,v])=>`<div class="detail-stat"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`).join("");
    $("cycleRows").innerHTML=cycles.slice().reverse().map(c=>`<tr><td>${c.cycle}</td><td>${money(c.receipts)}</td><td>${money(c.spent)}</td><td>${money(c.individual)}</td><td>${money(c.pac)}</td><td>${money(c.cash)}</td><td>${money(c.debt)}</td><td>${c.receipts?(c.spent/c.receipts*100).toFixed(1)+"%":"-"}</td></tr>`).join("");$("employerList").innerHTML=`<div class="notice">Employer-level donor groupings are not required to render the profile and are not fetched by default.</div>`;$("pacList").innerHTML=`<div class="notice">Detailed PAC transaction groupings are not required to render the profile and are not fetched by default.</div>`;
    if(window.Chart){const labels=cycles.map(c=>String(c.cycle));new Chart($("cycleChart"),{type:"bar",data:{labels,datasets:[{label:"Receipts",data:cycles.map(c=>c.receipts)},{label:"Spending",data:cycles.map(c=>c.spent)}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#aeb7c5"}}},scales:{x:{ticks:{color:"#8b96a7"}},y:{ticks:{color:"#8b96a7",callback:v=>new Intl.NumberFormat("en-US",{notation:"compact",style:"currency",currency:"USD"}).format(v)}}}}});new Chart($("mixChart"),{type:"doughnut",data:{labels:["Individuals","PAC / committees","Other"],datasets:[{data:[latest.individual,latest.pac,Math.max(0,latest.receipts-latest.individual-latest.pac)]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}});$("mixLegend").innerHTML=`Individuals ${money(latest.individual)} · PAC/committees ${money(latest.pac)}`}
  }
  async function init(){const id=queryId();if(!id){showFatal("No member ID was provided. Open a member from the chamber map first.");return}status("Loading profile","Frozen congressional roster");let roster;try{const r=await fetch(SNAPSHOT_URL,{cache:"force-cache"});if(!r.ok)throw new Error(`Roster request failed (${r.status})`);roster=(await r.json()).map(normalize)}catch(e){showFatal(e.message);return}const m=roster.find(x=>x.id===id);if(!m){showFatal(`Member ${id} was not found in the frozen September 24, 2026 roster.`);return}renderHero(m);renderStatic(m,roster);status("Profile loaded","Frozen roster · Sep 24, 2026");financePlaceholder("Campaign finance is loading separately. A finance-source failure will not hide the congressional profile.");try{const f=await loadFinance(m);renderFinance(m,f);status("Profile loaded",`Frozen roster · FEC cycle ${f.latest.cycle}`)}catch(e){financePlaceholder(e.message);status("Profile loaded","Frozen roster · finance unavailable")}
    $("copyLink").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(location.href);$("copyLink").textContent="Copied";setTimeout(()=>$("copyLink").textContent="Copy profile link",1200)}catch{$("copyLink").textContent="Copy failed"}})
  }
  init();
})();