import { clampTrimRange, detectMediaKind, formatDuration, noteFrequency, outputBaseName } from './media-core.js';
import { downloadBlob, formatBytes } from '../shared/files.js';

const $ = selector => document.querySelector(selector);
const drop=$('#mediaDrop'),picker=$('#mediaPicker'),workspace=$('#mediaWorkspace'),preview=$('#mediaPreview'),seek=$('#mediaSeek'),startInput=$('#trimStart'),endInput=$('#trimEnd'),readout=$('#mediaTimeReadout'),panel=$('#mediaActionPanel');
const progress=$('#mediaProgress'),progressLabel=$('#mediaProgressLabel'),progressValue=$('#mediaProgressValue'),progressBar=$('#mediaProgressBar'),downloadResultButton=$('#downloadMediaResult');
let file=null,kind='unknown',mediaElement=null,mediaUrl=null,duration=0,lastResult=null,mediabunnyPromise=null,metronomeTimer=null,activeRecorder=null;

function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function setProgress(label,fraction=null){progress.hidden=fraction==null;progressLabel.textContent=label;const f=Math.max(0,Math.min(1,Number(fraction)||0));progressBar.value=f;progressValue.textContent=`${Math.round(f*100)}%`;}
function clearProgress(){progress.hidden=true;progressBar.value=0;}
function setResult(blob,name){lastResult={blob,name};downloadResultButton.disabled=!blob;}
function closePanel(){panel.hidden=true;panel.innerHTML='';}
function openPanel(html){panel.innerHTML=html;panel.hidden=false;panel.scrollIntoView({block:'nearest'});}
function releaseMedia(){if(mediaUrl)URL.revokeObjectURL(mediaUrl);mediaUrl=null;if(mediaElement){try{mediaElement.pause();}catch{}mediaElement.remove();mediaElement=null;}}

function syncTimeline(){if(!mediaElement)return;const current=Math.max(0,Number(mediaElement.currentTime)||0);seek.value=String(Math.min(duration,current));readout.textContent=`${formatDuration(current)} / ${formatDuration(duration)}`;}
function resetRange(){startInput.value='0';endInput.value=String(duration||0);}
function currentRange(){return clampTrimRange(Number(startInput.value),Number(endInput.value),duration);}

function loadSource(nextFile){releaseMedia();file=nextFile||null;lastResult=null;downloadResultButton.disabled=true;closePanel();if(!file){workspace.hidden=true;drop.hidden=false;preview.innerHTML='';duration=0;return;}kind=detectMediaKind(file);workspace.hidden=false;drop.hidden=true;$('#mediaSourceName').textContent=file.name;$('#mediaSourceMeta').textContent=`${formatBytes(file.size)} · ${file.type||kind}`;mediaUrl=URL.createObjectURL(file);mediaElement=document.createElement(kind==='audio'?'audio':'video');mediaElement.controls=true;mediaElement.preload='metadata';mediaElement.playsInline=true;mediaElement.src=mediaUrl;preview.innerHTML='';preview.append(mediaElement);mediaElement.addEventListener('loadedmetadata',()=>{duration=Number(mediaElement.duration)||0;seek.max=String(duration||1);resetRange();syncTimeline();});mediaElement.addEventListener('timeupdate',syncTimeline);mediaElement.addEventListener('seeked',syncTimeline);}

async function loadMediabunny(){if(window.Mediabunny)return window.Mediabunny;if(!mediabunnyPromise)mediabunnyPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/mediabunny@1.59.1/dist/bundles/mediabunny.cjs';script.crossOrigin='anonymous';script.onload=()=>window.Mediabunny?resolve(window.Mediabunny):reject(new Error('Mediabunny did not initialize.'));script.onerror=()=>reject(new Error('Could not load Media Studio conversion engine.'));document.head.append(script);}).catch(e=>{mediabunnyPromise=null;throw e;});return mediabunnyPromise;}

function outputSpec(M,formatName){if(formatName==='mp4')return{format:new M.Mp4OutputFormat({fastStart:'in-memory'}),ext:'mp4',mime:'video/mp4'};if(formatName==='webm')return{format:new M.WebMOutputFormat(),ext:'webm',mime:'video/webm'};if(formatName==='wav')return{format:new M.WavOutputFormat(),ext:'wav',mime:'audio/wav'};throw new Error(`Unsupported output format: ${formatName}`);}

async function convertWithMediabunny({formatName,trim=null,video=null,audio=undefined}={}){if(!file)throw new Error('Choose media first.');setProgress('Loading media engine…',0);const M=await loadMediabunny();const spec=outputSpec(M,formatName);const input=new M.Input({source:new M.BlobSource(file),formats:M.ALL_FORMATS});const target=new M.BufferTarget();const output=new M.Output({format:spec.format,target});const options={input,output};if(trim)options.trim=trim;if(video!==null)options.video=video;if(audio!==undefined)options.audio=audio;const conversion=await M.Conversion.init(options);if(!conversion.isValid){const why=(conversion.discardedTracks||[]).map(x=>x.reason).filter(Boolean).join(', ');throw new Error(`This conversion is not supported in this browser${why?`: ${why}`:''}.`);}conversion.onProgress=p=>setProgress('Processing media locally…',Number(p)||0);await conversion.execute();const buffer=target.buffer;if(!buffer)throw new Error('Media conversion finished without output.');const blob=new Blob([buffer],{type:spec.mime});const name=`${outputBaseName(file.name)}-toolbox.${spec.ext}`;setResult(blob,name);setProgress('Complete',1);return{blob,name};}

function showTrim(){if(!file)return;const range=currentRange();openPanel(`<div class="media-form"><div class="media-time-head"><strong>Trim ${kind}</strong><button id="closeMediaPanel" class="tb-toolbutton">Close</button></div><p>Exports only <strong>${formatDuration(range.start)} → ${formatDuration(range.end)}</strong>. Audio exports as WAV; video uses MP4 for MP4/MOV sources and WebM otherwise.</p><div class="media-actions"><button id="runTrim" class="media-primary">Trim & export</button></div><div id="mediaPanelStatus"></div></div>`);$('#closeMediaPanel').onclick=closePanel;$('#runTrim').onclick=async()=>{const r=currentRange();if(r.duration<=0)return;try{const formatName=kind==='audio'?'wav':(/mp4|quicktime/i.test(file.type)?'mp4':'webm');const result=await convertWithMediabunny({formatName,trim:{start:r.start,end:r.end}});$('#mediaPanelStatus').textContent=`Ready · ${formatBytes(result.blob.size)}`;}catch(e){$('#mediaPanelStatus').textContent=e.message;}finally{setTimeout(clearProgress,700);}};}

function showConvert(){if(!file)return;const videoFields=kind==='video'?`<label>Format<select id="convertFormat"><option value="mp4">MP4</option><option value="webm">WebM</option></select></label><label>Fit<select id="videoFit"><option value="contain">Contain</option><option value="cover">Cover</option><option value="fill">Fill</option></select></label><label>Width<input id="videoWidth" type="number" min="1" placeholder="original"></label><label>Height<input id="videoHeight" type="number" min="1" placeholder="original"></label><label>Rotate<select id="videoRotate"><option value="0">0°</option><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></label><label><span><input id="videoFlip" type="checkbox"> Flip horizontally</span></label><label>Crop left<input id="cropLeft" type="number" min="0" placeholder="0"></label><label>Crop top<input id="cropTop" type="number" min="0" placeholder="0"></label><label>Crop width<input id="cropWidth" type="number" min="1" placeholder="full"></label><label>Crop height<input id="cropHeight" type="number" min="1" placeholder="full"></label>`:`<label>Format<select id="convertFormat"><option value="wav">WAV</option><option value="webm">WebM audio</option></select></label>`;openPanel(`<div class="media-form"><div class="media-time-head"><strong>Convert / transform</strong><button id="closeMediaPanel" class="tb-toolbutton">Close</button></div><div class="media-form-grid">${videoFields}</div><div class="media-actions"><button id="runConvert" class="media-primary">Convert</button></div><div id="mediaPanelStatus"></div></div>`);$('#closeMediaPanel').onclick=closePanel;$('#runConvert').onclick=async()=>{try{let formatName=$('#convertFormat').value;let video=undefined;if(kind==='video'){video={};const width=Number($('#videoWidth').value),height=Number($('#videoHeight').value);if(width)video.width=width;if(height)video.height=height;if(width&&height)video.fit=$('#videoFit').value;const rotate=Number($('#videoRotate').value);if(rotate)video.rotate=rotate;video.flip=$('#videoFlip').checked||undefined;const cw=Number($('#cropWidth').value),ch=Number($('#cropHeight').value);if(cw&&ch)video.crop={left:Number($('#cropLeft').value)||0,top:Number($('#cropTop').value)||0,width:cw,height:ch};}const result=await convertWithMediabunny({formatName,video});$('#mediaPanelStatus').textContent=`Ready · ${formatBytes(result.blob.size)}`;}catch(e){$('#mediaPanelStatus').textContent=e.message;}finally{setTimeout(clearProgress,700);}};}

function audioBufferToWav(channels,sampleRate){const channelCount=channels.length,frames=channels[0]?.length||0,bytesPerSample=2,blockAlign=channelCount*bytesPerSample,buffer=new ArrayBuffer(44+frames*blockAlign),view=new DataView(buffer);const write=(offset,text)=>{for(let i=0;i<text.length;i++)view.setUint8(offset+i,text.charCodeAt(i));};write(0,'RIFF');view.setUint32(4,36+frames*blockAlign,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channelCount,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*blockAlign,true);view.setUint16(32,blockAlign,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,frames*blockAlign,true);let offset=44;for(let i=0;i<frames;i++)for(let c=0;c<channelCount;c++){const s=Math.max(-1,Math.min(1,channels[c][i]||0));view.setInt16(offset,s<0?s*0x8000:s*0x7fff,true);offset+=2;}return buffer;}

async function editAudio(){if(!file||kind!=='audio')return;const ctx=new AudioContext();try{const decoded=await ctx.decodeAudioData(await file.arrayBuffer());const r=currentRange();const start=Math.floor(r.start*decoded.sampleRate),end=Math.min(decoded.length,Math.ceil(r.end*decoded.sampleRate));const channels=[];const speed=Math.max(.25,Math.min(4,Number($('#audioSpeed').value)||1));const gain=Math.max(0,Number($('#audioGain').value)||1);const reverse=$('#audioReverse').checked,normalize=$('#audioNormalize').checked,fade=Math.max(0,Number($('#audioFade').value)||0);const sourceLength=Math.max(1,end-start),outputLength=Math.max(1,Math.floor(sourceLength/speed));let peak=0;for(let c=0;c<decoded.numberOfChannels;c++){const src=decoded.getChannelData(c);const out=new Float32Array(outputLength);for(let i=0;i<outputLength;i++){const pos=start+i*speed;const p0=Math.min(end-1,Math.floor(pos)),p1=Math.min(end-1,p0+1),t=pos-p0;out[i]=(src[p0]*(1-t)+src[p1]*t)*gain;peak=Math.max(peak,Math.abs(out[i]));}if(reverse)out.reverse();channels.push(out);}const scale=normalize&&peak>0?1/peak:1;const fadeFrames=Math.min(Math.floor(fade*decoded.sampleRate),Math.floor(outputLength/2));for(const out of channels)for(let i=0;i<out.length;i++){let factor=scale;if(fadeFrames&&i<fadeFrames)factor*=i/fadeFrames;if(fadeFrames&&i>=out.length-fadeFrames)factor*=(out.length-1-i)/fadeFrames;out[i]*=factor;}const wav=audioBufferToWav(channels,decoded.sampleRate);const blob=new Blob([wav],{type:'audio/wav'});const name=`${outputBaseName(file.name)}-edited.wav`;setResult(blob,name);return{blob,name};}finally{ctx.close();}}

function showAudioEdit(){if(kind!=='audio'){openPanel(`<div class="media-time-head"><strong>Audio edit</strong><button id="closeMediaPanel" class="tb-toolbutton">Close</button></div><p>Load an audio file to use volume, speed, reverse, normalization and fades.</p>`);$('#closeMediaPanel').onclick=closePanel;return;}openPanel(`<div class="media-form"><div class="media-time-head"><strong>Audio edit</strong><button id="closeMediaPanel" class="tb-toolbutton">Close</button></div><div class="media-form-grid"><label>Volume<input id="audioGain" type="number" min="0" max="4" step="0.05" value="1"></label><label>Speed / pitch linked<input id="audioSpeed" type="number" min="0.25" max="4" step="0.05" value="1"></label><label>Fade in/out seconds<input id="audioFade" type="number" min="0" step="0.05" value="0"></label><label><span><input id="audioNormalize" type="checkbox"> Normalize peak</span><span><input id="audioReverse" type="checkbox"> Reverse</span></label></div><div class="media-actions"><button id="runAudioEdit" class="media-primary">Render WAV</button></div><div id="mediaPanelStatus"></div></div>`);$('#closeMediaPanel').onclick=closePanel;$('#runAudioEdit').onclick=async()=>{setProgress('Rendering audio locally…',.2);try{const result=await editAudio();$('#mediaPanelStatus').textContent=`Ready · ${formatBytes(result.blob.size)}`;setProgress('Complete',1);}catch(e){$('#mediaPanelStatus').textContent=e.message;}finally{setTimeout(clearProgress,700);}};}

function showExtractAudio(){if(!file||kind!=='video')return;openPanel(`<div class="media-form"><div class="media-time-head"><strong>Extract audio</strong><button id="closeMediaPanel" class="tb-toolbutton">Close</button></div><p>Exports the selected timeline range as WAV and drops the video track.</p><button id="runExtract" class="media-primary">Extract WAV</button><div id="mediaPanelStatus"></div></div>`);$('#closeMediaPanel').onclick=closePanel;$('#runExtract').onclick=async()=>{try{const r=currentRange(),result=await convertWithMediabunny({formatName:'wav',trim:{start:r.start,end:r.end},video:{discard:true}});$('#mediaPanelStatus').textContent=`Ready · ${formatBytes(result.blob.size)}`;}catch(e){$('#mediaPanelStatus').textContent=e.message;}finally{setTimeout(clearProgress,700);}};}

async function inspect(){if(!file)return;openPanel(`<div class="media-time-head"><strong>Media info</strong><button id="closeMediaPanel" class="tb-toolbutton">Close</button></div><p>Reading container and tracks…</p>`);$('#closeMediaPanel').onclick=closePanel;try{const M=await loadMediabunny();const input=new M.Input({source:new M.BlobSource(file),formats:M.ALL_FORMATS});const preciseDuration=await input.computeDuration();const video=await input.getPrimaryVideoTrack(),audio=await input.getPrimaryAudioTrack();const rows=[['File',file.name],['Size',formatBytes(file.size)],['MIME',file.type||'unknown'],['Duration',formatDuration(preciseDuration)]];if(video){rows.push(['Video codec',await video.getCodec()||'unknown'],['Video size',`${await video.getDisplayWidth()}×${await video.getDisplayHeight()}`],['Video bitrate',formatBitrate(await video.getAverageBitrate())],['Rotation',`${await video.getRotation()}°`]);try{const fps=await video.computeFrameRateMetrics();rows.push(['Frame rate',`${Number(fps.averageFrameRate||fps.average||0).toFixed(3)} fps`]);}catch{}}if(audio)rows.push(['Audio codec',await audio.getCodec()||'unknown'],['Sample rate',`${await audio.getSampleRate()} Hz`],['Channels',String(await audio.getNumberOfChannels())],['Audio bitrate',formatBitrate(await audio.getAverageBitrate())]);panel.innerHTML=`<div class="media-time-head"><strong>Media info</strong><button id="closeMediaPanel" class="tb-toolbutton">Close</button></div><div class="media-info">${rows.map(([a,b])=>`<div class="media-info-row"><span>${escapeHtml(a)}</span><code>${escapeHtml(b)}</code></div>`).join('')}</div>`;$('#closeMediaPanel').onclick=closePanel;}catch(e){panel.insertAdjacentHTML('beforeend',`<p>${escapeHtml(e.message)}</p>`);}}
function formatBitrate(value){return value?`${(value/1000).toFixed(0)} kb/s`:'unknown';}

function bestRecorderMime(video){const candidates=video?['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm']:['audio/webm;codecs=opus','audio/webm'];return candidates.find(type=>MediaRecorder.isTypeSupported(type))||'';}
async function startRecording(mode,status){if(activeRecorder)return;let streams=[];try{let stream;if(mode==='mic')stream=await navigator.mediaDevices.getUserMedia({audio:true});else if(mode==='camera')stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});else{const display=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});streams.push(display);if(mode==='screen-mic'){const mic=await navigator.mediaDevices.getUserMedia({audio:true});streams.push(mic);stream=new MediaStream([...display.getVideoTracks(),...display.getAudioTracks(),...mic.getAudioTracks()]);}else stream=display;}streams.push(stream);const hasVideo=stream.getVideoTracks().length>0,chunks=[],recorder=new MediaRecorder(stream,{mimeType:bestRecorderMime(hasVideo)});activeRecorder={recorder,streams:[...new Set(streams)]};recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data);};recorder.onstop=()=>{const blob=new Blob(chunks,{type:recorder.mimeType||bestRecorderMime(hasVideo)}),name=`toolbox-recording-${new Date().toISOString().replace(/[:.]/g,'-')}.${hasVideo?'webm':'webm'}`;setResult(blob,name);status.textContent=`Recording ready · ${formatBytes(blob.size)}`;status.classList.remove('live');for(const s of activeRecorder?.streams||[])for(const track of s.getTracks())track.stop();activeRecorder=null;};recorder.start(250);status.textContent='Recording… press Stop when finished.';status.classList.add('live');}catch(e){status.textContent=e.message;for(const s of streams)for(const track of s.getTracks())track.stop();activeRecorder=null;}}
function showRecorder(){openPanel(`<div class="media-form"><div class="media-time-head"><strong>Recorder</strong><button id="closeMediaPanel" class="tb-toolbutton">Close</button></div><div class="media-actions"><button data-record="mic" class="tb-toolbutton">Microphone</button><button data-record="camera" class="tb-toolbutton">Camera + mic</button><button data-record="screen" class="tb-toolbutton">Screen</button><button data-record="screen-mic" class="tb-toolbutton">Screen + mic</button><button id="stopRecording" class="media-primary">Stop</button></div><div id="recordStatus" class="media-record-status">Choose a recorder mode. Your browser will ask for permission.</div></div>`);const status=$('#recordStatus');$('#closeMediaPanel').onclick=()=>{if(!activeRecorder)closePanel();};panel.querySelectorAll('[data-record]').forEach(button=>button.onclick=()=>startRecording(button.dataset.record,status));$('#stopRecording').onclick=()=>activeRecorder?.recorder?.stop();}

function makeToneWav(frequency,durationSeconds,wave='sine',sampleRate=48000){const length=Math.max(1,Math.floor(durationSeconds*sampleRate)),channel=new Float32Array(length);for(let i=0;i<length;i++){const phase=2*Math.PI*frequency*i/sampleRate;channel[i]=wave==='square'?(Math.sin(phase)>=0?.7:-.7):wave==='triangle'?(2/Math.PI)*Math.asin(Math.sin(phase)):.75*Math.sin(phase);const edge=Math.min(1,i/(sampleRate*.01),(length-1-i)/(sampleRate*.01));channel[i]*=Math.max(0,edge);}return audioBufferToWav([channel],sampleRate);}
function playTone(frequency,durationSeconds,wave){const ctx=new AudioContext(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=wave;osc.frequency.value=frequency;gain.gain.value=.15;osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+durationSeconds);osc.onended=()=>ctx.close();}
function showTone(){openPanel(`<div class="media-form"><div class="media-time-head"><strong>Tone / metronome</strong><button id="closeMediaPanel" class="tb-toolbutton">Close</button></div><div class="media-form-grid"><label>Frequency (Hz)<input id="toneHz" type="number" min="20" max="20000" value="440"></label><label>Note<input id="toneNote" type="text" value="A4"></label><label>Wave<select id="toneWave"><option>sine</option><option>square</option><option>triangle</option></select></label><label>Duration seconds<input id="toneDuration" type="number" min="0.05" max="30" step="0.05" value="1"></label><label>BPM<input id="metroBpm" type="number" min="20" max="300" value="120"></label></div><div class="media-actions"><button id="noteToHz" class="tb-toolbutton">Note → Hz</button><button id="playTone" class="tb-toolbutton">Play tone</button><button id="downloadTone" class="media-primary">Create WAV</button><button id="toggleMetro" class="tb-toolbutton">Start metronome</button></div><div id="toneStatus"></div></div>`);$('#closeMediaPanel').onclick=()=>{stopMetronome();closePanel();};$('#noteToHz').onclick=()=>{const hz=noteFrequency($('#toneNote').value);if(Number.isFinite(hz))$('#toneHz').value=hz.toFixed(3);};$('#playTone').onclick=()=>playTone(Number($('#toneHz').value)||440,Number($('#toneDuration').value)||1,$('#toneWave').value);$('#downloadTone').onclick=()=>{const hz=Number($('#toneHz').value)||440,d=Number($('#toneDuration').value)||1,w=$('#toneWave').value,blob=new Blob([makeToneWav(hz,d,w)],{type:'audio/wav'}),name=`tone-${Math.round(hz)}hz.wav`;setResult(blob,name);$('#toneStatus').textContent=`WAV ready · ${formatBytes(blob.size)}`;};$('#toggleMetro').onclick=event=>{if(metronomeTimer){stopMetronome();event.currentTarget.textContent='Start metronome';return;}const bpm=Math.max(20,Math.min(300,Number($('#metroBpm').value)||120));playTone(1200,.04,'sine');metronomeTimer=setInterval(()=>playTone(1200,.04,'sine'),60000/bpm);event.currentTarget.textContent='Stop metronome';};}
function stopMetronome(){if(metronomeTimer){clearInterval(metronomeTimer);metronomeTimer=null;}}

seek.addEventListener('input',()=>{if(mediaElement){mediaElement.currentTime=Number(seek.value)||0;syncTimeline();}});$('#setStartHere').onclick=()=>{startInput.value=String(Number(mediaElement?.currentTime)||0);};$('#setEndHere').onclick=()=>{endInput.value=String(Number(mediaElement?.currentTime)||0);};$('#mediaResetRange').onclick=resetRange;
drop.onclick=()=>picker.click();drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();picker.click();}};for(const type of ['dragenter','dragover'])drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add('drag');});for(const type of ['dragleave','drop'])drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove('drag');});drop.addEventListener('drop',e=>loadSource(e.dataTransfer.files?.[0]));picker.onchange=()=>{loadSource(picker.files?.[0]);picker.value='';};$('#replaceMedia').onclick=()=>picker.click();$('#clearMedia').onclick=()=>loadSource(null);
$('#trimMedia').onclick=showTrim;$('#convertMedia').onclick=showConvert;$('#audioEdit').onclick=showAudioEdit;$('#extractAudio').onclick=showExtractAudio;$('#recordMedia').onclick=showRecorder;$('#toneGenerator').onclick=showTone;$('#inspectMedia').onclick=inspect;document.querySelectorAll('[data-media-quick]').forEach(button=>button.onclick=()=>button.dataset.mediaQuick==='record'?showRecorder():showTone());downloadResultButton.onclick=()=>lastResult&&downloadBlob(lastResult.blob,lastResult.name);
window.addEventListener('beforeunload',()=>{releaseMedia();stopMetronome();try{activeRecorder?.recorder?.stop();}catch{}});
loadSource(null);
