const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const Lab=window.VCTCompLab;
const POOL=Lab.DEFAULT_PLAYER_POOL;
const MAPS_FALLBACK=['Abyss','Ascent','Haven','Lotus','Split','Summit','Sunset'];
const REGIONS=['All','Americas','EMEA','Pacific','China'];
const SETUPS={
  Abyss:{attack:[[20,75,'A pressure'],[35,64,'A link'],[50,76,'mid flex'],[65,63,'B link'],[80,75,'B pressure']],defense:[[22,28,'A anchor'],[37,40,'A link'],[50,31,'mid'],[63,40,'B link'],[78,28,'B anchor']]},
  Ascent:{attack:[[20,75,'A Main'],[38,64,'cat / mid'],[50,76,'mid'],[64,62,'market'],[80,75,'B Main']],defense:[[22,28,'A'],[38,38,'tree'],[50,31,'mid'],[63,39,'market'],[78,28,'B']]},
  Haven:{attack:[[18,73,'A pressure'],[36,62,'A / mid'],[50,73,'Garage'],[64,61,'C link'],[82,72,'C pressure']],defense:[[18,28,'A anchor'],[36,39,'A link'],[50,29,'Garage'],[64,39,'C link'],[82,28,'C anchor']]},
  Lotus:{attack:[[18,75,'A pressure'],[34,63,'A link'],[50,73,'B pressure'],[66,63,'C link'],[82,75,'C pressure']],defense:[[18,28,'A'],[34,39,'A link'],[50,30,'B'],[66,39,'C link'],[82,28,'C']]},
  Split:{attack:[[20,75,'A Main'],[38,62,'A ramps'],[50,74,'mid'],[64,61,'B heaven'],[80,75,'B Main']],defense:[[22,28,'A'],[38,39,'A heaven'],[50,30,'mid'],[64,39,'B heaven'],[78,28,'B']]},
  Summit:{attack:[[20,75,'A pressure'],[37,63,'A link'],[50,75,'central'],[64,62,'B link'],[80,75,'B pressure']],defense:[[22,28,'A'],[37,40,'A link'],[50,30,'central'],[64,40,'B link'],[78,28,'B']]},
  Sunset:{attack:[[20,75,'A Main'],[38,64,'A link'],[50,75,'mid'],[64,63,'market'],[80,75,'B Main']],defense:[[22,28,'A'],[38,40,'A link'],[50,30,'mid'],[64,40,'market'],[78,28,'B']]}
};
const state={data:null,mode:localStorage.getItem('vctMode')||'scout',map:localStorage.getItem('vctMap')||'Haven',teamId:Number(localStorage.getItem('vctTeam'))||120,region:'All',query:'',scoutView:'team',side:'attack',labTab:'recommend',activePlayers:Lab.defaultActivePlayers(POOL),manual:{},agentAssets:new Map(),mapAssets:new Map(),recCache:new Map(),selectedRec:0,recent:JSON.parse(localStorage.getItem('vctRecent')||'[]')};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtPct(v){return v==null?'n/a':`${Number(v).toFixed(1)}%`}
function dateLabel(s){if(!s)return'n/a';const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function agentAsset(name){return state.agentAssets.get(String(name).toLowerCase())||null}
function agentImg(name){const u=agentAsset(name);return u?`<img src="${esc(u)}" alt="">`:`<span style="width:25px;height:25px;display:grid;place-items:center">${esc(String(name).slice(0,2).toUpperCase())}</span>`}
function agentPill(name,showRole=true){return `<span class="agent">${agentImg(name)}<span>${esc(name)}${showRole?` <small>${esc(Lab.roleOf(name,POOL))}</small>`:''}</span></span>`}
function metric(k,v,s=''){return `<div class="metric"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div>${s?`<div class="s">${esc(s)}</div>`:''}</div>`}
function currentTeam(){return state.data?.teams?.find(t=>Number(t.id)===Number(state.teamId))||state.data?.teams?.[0]||null}
function mapMeta(){return state.data?.meta_by_map?.[state.map]||{agent_pick_rates:[],top_compositions:[],team_side_maps:0}}
function collectObserved(){const rows=[];for(const t of state.data?.teams||[]){const m=t.maps?.[state.map];for(const c of m?.compositions||[])rows.push({...c,team:t.name,tag:t.tag,region:t.region})}return rows}
function setMode(mode){state.mode=mode;localStorage.setItem('vctMode',mode);render()}
function setMap(map){state.map=map;localStorage.setItem('vctMap',map);state.recCache.clear();state.manual={};state.selectedRec=0;render()}
function rememberTeam(id){state.recent=[Number(id),...state.recent.filter(x=>Number(x)!==Number(id))].slice(0,5);localStorage.setItem('vctRecent',JSON.stringify(state.recent))}
function selectTeam(id){state.teamId=Number(id);localStorage.setItem('vctTeam',String(id));rememberTeam(id);renderScout()}
function renderMapTabs(){const maps=state.data?.map_pool?.length?state.data.map_pool:MAPS_FALLBACK;$('#mapTabs').innerHTML=maps.map(m=>`<button class="mapbtn ${m===state.map?'active':''}" data-map="${esc(m)}">${esc(m)}</button>`).join('');$$('[data-map]').forEach(b=>b.onclick=()=>setMap(b.dataset.map))}
function renderModeButtons(){$$('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===state.mode);b.onclick=()=>setMode(b.dataset.mode)})}
function renderStatus(){const d=state.data;$('#freshness').textContent=d?.generated_at?dateLabel(d.generated_at):'unavailable';$('#window').textContent=d?`${d.window_start} to ${d.window_end}`:'unavailable';$('#datastate').textContent=d?.status||'unavailable'}
function render(){renderModeButtons();renderMapTabs();renderStatus();$('#scoutWorkspace').classList.toggle('hidden',state.mode!=='scout');$('#labWorkspace').classList.toggle('hidden',state.mode!=='lab');if(state.mode==='scout')renderScout();else renderLab()}
function teamPickerHtml(){
  const teams=state.data?.teams||[],selected=currentTeam();let shown=teams.filter(t=>(state.region==='All'||t.region===state.region)&&(!state.query||`${t.name} ${t.tag}`.toLowerCase().includes(state.query.toLowerCase())));
  const recent=state.recent.map(id=>teams.find(t=>Number(t.id)===Number(id))).filter(Boolean);
  return `<section class="panel team-picker"><div class="teamtop"><div><span class="label">Selected team</span><div class="selected-team"><div class="teamtag">${esc(selected?.tag||'?')}</div><div><b>${esc(selected?.name||'No team')}</b><span>${esc(selected?.region||'')}</span></div></div></div><div><label class="label" for="teamSearch">Find a team</label><input id="teamSearch" class="search" placeholder="Type 100T, Liquid, Paper Rex..." value="${esc(state.query)}"></div></div><div class="pickerfilters">${REGIONS.map(r=>`<button class="regionbtn ${r===state.region?'active':''}" data-region="${r}">${r}</button>`).join('')}</div><div class="teamgrid">${shown.map(t=>`<button class="teambtn ${Number(t.id)===Number(state.teamId)?'active':''}" data-team="${t.id}"><b>${esc(t.tag)} · ${esc(t.name)}</b><span>${esc(t.region)}</span></button>`).join('')}</div>${recent.length?`<div class="recentrow"><span>Recent:</span>${recent.map(t=>`<button class="recentbtn" data-team="${t.id}">${esc(t.tag)}</button>`).join('')}</div>`:''}</section>`
}
function bindTeamPicker(){const s=$('#teamSearch');if(s){s.oninput=e=>{state.query=e.target.value;renderScout()};setTimeout(()=>{const n=$('#teamSearch');if(n&&document.activeElement===document.body&&state.query)n.focus()},0)}$$('[data-region]').forEach(b=>b.onclick=()=>{state.region=b.dataset.region;renderScout()});$$('[data-team]').forEach(b=>b.onclick=()=>selectTeam(b.dataset.team))}
function scoutMapData(){if(state.scoutView==='meta')return mapMeta();return currentTeam()?.maps?.[state.map]||null}
function renderScout(){
  const root=$('#scoutWorkspace');if(!state.data){root.innerHTML='<div class="panel empty">Loading scouting data...</div>';return}
  root.innerHTML=teamPickerHtml()+`<section class="panel" style="margin-top:16px"><div class="panelhead"><div><h2 class="paneltitle">Scout board</h2><p class="panelsub">Team view shows one team. Meta view aggregates the current Champions field.</p></div><div class="boardtabs"><button class="tabbtn ${state.scoutView==='team'?'active':''}" data-scoutview="team">Team</button><button class="tabbtn ${state.scoutView==='meta'?'active':''}" data-scoutview="meta">Meta</button></div></div><div id="scoutBoard" class="bodypad"></div></section>`;
  bindTeamPicker();$$('[data-scoutview]').forEach(b=>b.onclick=()=>{state.scoutView=b.dataset.scoutview;renderScout()});renderScoutBoard()
}
function renderScoutBoard(){const mount=$('#scoutBoard'),team=currentTeam(),row=scoutMapData();if(!row){mount.innerHTML=`<div class="empty">No ${esc(state.scoutView)} observations for ${esc(state.map)} in the current snapshot.</div>`;return}
  if(state.scoutView==='meta') mount.innerHTML=renderMetaBoard(row); else mount.innerHTML=renderTeamBoard(team,row);bindSideButtons()
}
function renderTeamBoard(team,row){const latest=row.latest,common=row.common;return `<div class="two"><div class="stack"><section class="panel"><div class="panelhead"><div><h3 class="paneltitle">${esc(team.name)} on ${esc(state.map)}</h3><p class="panelsub">Latest observed ${latest?`${dateLabel(latest.date)} vs ${esc(latest.opponent)}`:'match data'}.</p></div></div><div class="metrics">${metric('Maps',row.games,`${row.wins}W · ${row.losses}L`)}${metric('Map win rate',fmtPct(row.win_rate))}${metric('Attack rounds',fmtPct(row.attack_round_win_rate))}${metric('Defense rounds',fmtPct(row.defense_round_win_rate))}</div></section><section class="panel"><div class="panelhead"><div><h3 class="paneltitle">Agent composition</h3><p class="panelsub">Latest observed lineup and most-used lineup in this snapshot.</p></div></div><div class="bodypad"><div class="compgrid"><div class="compcard accent"><div class="compk">Latest observed</div><div class="agents">${(latest?.agents||[]).map(a=>agentPill(a)).join('')}</div><div class="compmeta">${latest?`${latest.result} ${latest.team_score}-${latest.opponent_score} vs ${esc(latest.opponent)} · ${dateLabel(latest.date)}`:'No recent comp'}</div></div><div class="compcard"><div class="compk">Most used</div><div class="agents">${(common?.agents||[]).map(a=>agentPill(a)).join('')}</div><div class="compmeta">${common?`${common.games} map${common.games===1?'':'s'} · ${fmtPct(common.win_rate)} observed win rate`:'No common comp'}</div></div></div></div></section><section class="panel"><div class="panelhead"><div><h3 class="paneltitle">Agent pick board</h3><p class="panelsub">Share of ${team.tag}'s observed ${state.map} maps using each agent.</p></div></div>${renderBars(row.agent_pick_rates||[])}</section><section class="panel"><div class="panelhead"><div><h3 class="paneltitle">Composition history</h3><p class="panelsub">Most frequent five-agent sets.</p></div></div>${renderHistory(row.compositions||[])}</section></div>${renderMapPanel(latest?.agents||common?.agents||[],`${team.tag} role-based ${state.side} setup`)}</div>`}
function renderMetaBoard(row){const top=row.top_compositions?.[0];return `<div class="two"><div class="stack"><section class="panel"><div class="panelhead"><div><h3 class="paneltitle">Champions field meta · ${esc(state.map)}</h3><p class="panelsub">Aggregated team-side observations across the teams in this dataset.</p></div></div><div class="metrics">${metric('Team-side maps',row.team_side_maps||0)}${metric('Latest observed',dateLabel(row.latest_date||''))}${metric('Top agent',row.agent_pick_rates?.[0]?.agent||'n/a',fmtPct(row.agent_pick_rates?.[0]?.rate))}${metric('Top comp sample',top?.games||0,'observed maps')}</div></section><section class="panel"><div class="panelhead"><div><h3 class="paneltitle">Map pick rates</h3><p class="panelsub">Agent frequency across the current field.</p></div></div>${renderBars(row.agent_pick_rates||[])}</section><section class="panel"><div class="panelhead"><div><h3 class="paneltitle">Common VCT comps</h3><p class="panelsub">Observed five-agent sets aggregated across teams.</p></div></div>${renderHistory(row.top_compositions||[])}</section></div>${renderMapPanel(top?.agents||[],`Field template using the most-observed comp`)}</div>`}
function renderBars(rows){if(!rows.length)return'<div class="empty">No agent-rate data.</div>';const max=Math.max(...rows.map(x=>Number(x.rate)||0),1);return `<div class="chart">${rows.slice(0,14).map(x=>`<div class="barrow"><div class="barname">${agentImg(x.agent)}<span>${esc(x.agent)}</span></div><div class="track"><div class="fill" style="width:${Math.max(2,(Number(x.rate)||0)/max*100)}%"></div></div><div class="barval">${fmtPct(x.rate)}</div></div>`).join('')}</div>`}
function renderHistory(rows){if(!rows.length)return'<div class="empty">No composition history.</div>';return `<div class="history">${rows.slice(0,8).map(c=>`<div class="historyrow"><div><b>${c.games||0}x</b></div><div class="tinyagents">${(c.agents||[]).map(a=>`<span class="tinyagent">${esc(a)}</span>`).join('')}</div><div class="good">${fmtPct(c.win_rate)}</div></div>`).join('')}</div>`}
function renderMapPanel(agents,title){const asset=state.mapAssets.get(state.map),spots=(SETUPS[state.map]?.[state.side]||SETUPS.Haven[state.side]);return `<section class="panel map-panel"><div class="maptop"><div><h3 class="paneltitle">${esc(state.map)} setup board</h3><p class="panelsub">${esc(title)}.</p></div><div class="setupseg"><button class="smallbtn ${state.side==='attack'?'active':''}" data-side="attack">Attack</button><button class="smallbtn ${state.side==='defense'?'active':''}" data-side="defense">Defense</button></div></div><div class="mapstage">${asset?`<img class="mapimg" src="${esc(asset)}" alt="${esc(state.map)} map">`:`<div class="mapfallback">${esc(state.map)}</div>`}${spots.map((p,i)=>{const a=agents[i]||'?';return `<div class="marker" style="left:${p[0]}%;top:${p[1]}%"><div class="markericon">${a==='?'?'?':agentImg(a)}</div><div class="markerlabel">${esc(a)} · ${esc(p[2])}</div></div>`}).join('')}</div><div class="mapnote">These markers are role-based setup templates for orientation and planning. They are not VCT tracking coordinates.</div></section>`}
function bindSideButtons(){$$('[data-side]').forEach(b=>b.onclick=()=>{state.side=b.dataset.side;if(state.mode==='scout')renderScoutBoard();else renderLab()})}
