const RAW={
 aiden:{x:4.25,y:-3.23,ax:4.25,ay:-.25,bx:5.83,by:-4.29,cx:3.13,cy:6.15,dx:-2.45,dy:-3.44,ex:-2.45,ey:5,fx:1.17,fy:-7,gx:-1,gy:1.5,hx:.67,hy:-7.67,ix:-2,iy:-2.5,ja:4,jb:0,jc:2.67,jd:-1.25},
 tommy:{x:-4.78,y:-1.02,ax:-4.79,ay:2.08,bx:.11,by:.11,cx:-1,cy:-2,dx:-3.65,dy:-3.75,ex:7,ey:-.75,fx:-.4,fy:-4,gx:-4.2,gy:-.33,hx:-.33,hy:1.67,ix:.25,iy:4.25,ja:2.67,jb:-1.5,jc:-.67,jd:-2},
 justin:{x:5.63,y:-1.77,ax:5.63,ay:-.75,bx:3.33,by:-2.06,cx:2.25,cy:5.77,dx:2.27,dy:-.44,ex:-1.09,ey:0,fx:-1,fy:-3,gx:-6,gy:3.83,hx:0,hy:-1.67,ix:1,iy:0,ja:4.33,jb:3.5,jc:0,jd:-1.25},
 taylor:{x:4.13,y:1.84,ax:4.13,ay:-3.75,bx:-10,by:1.59,cx:3.75,cy:9.08,dx:7.45,dy:-2.33,ex:-6.09,ey:-3.33,fx:.67,fy:5,gx:-2,gy:10,hx:10,hy:-3.33,ix:7.5,iy:-7.5,ja:10,jb:-5,jc:1,jd:0}
};
const P=['aiden','tommy','justin','taylor'],N={aiden:'Aiden',tommy:'Tommy',justin:'Justin',taylor:'Taylor'},C={aiden:[255,90,95],tommy:[79,124,255],justin:[46,204,113],taylor:[255,176,32]};
const ctl={aiden:document.getElementById('showAiden'),tommy:document.getElementById('showTommy'),justin:document.getElementById('showJustin'),taylor:document.getElementById('showTaylor'),average:document.getElementById('showAverage')};
let showPeopleMarkers=true;
function selectedPeople(){return P.filter(p=>ctl[p].checked)}
function selectedAverage(){const selected=selectedPeople();if(!selected.length)return null;const out={};Object.keys(RAW.aiden).forEach(k=>out[k]=selected.reduce((s,p)=>s+RAW[p][k],0)/selected.length);return out}
const PAN=[['x','y',115,450],['ax','ay',735,450],['bx','by',1360,450],['cx','cy',1985,450],['dx','dy',115,945],['ex','ey',735,945],['fx','fy',1360,945],['gx','gy',1985,945],['hx','hy',115,1450],['ix','iy',735,1450]], MOR=[['ja',1058],['jb',1151],['jc',1246],['jd',1340]];
const can=document.getElementById('compassCanvas'),ctx=can.getContext('2d'),bg=new Image();bg.crossOrigin='anonymous';
function pt(a,v){return[a[2]+400*(v[a[0]]+10)/20,a[3]-400*(v[a[1]]+10)/20]}
function mpt(a,v){return[1672+400*(v[a[0]]+10)/20,a[1]]}
function dot(x,y,c){ctx.save();ctx.shadowColor='#0008';ctx.shadowBlur=7;ctx.beginPath();ctx.arc(x,y,15,0,Math.PI*2);ctx.fillStyle=`rgb(${c})`;ctx.fill();ctx.lineWidth=5;ctx.strokeStyle='#fff';ctx.stroke();ctx.shadowBlur=0;ctx.lineWidth=2;ctx.strokeStyle='#111827';ctx.stroke();ctx.restore()}
function avg(x,y){ctx.save();ctx.translate(x,y);ctx.shadowColor='#0009';ctx.shadowBlur=9;ctx.beginPath();ctx.moveTo(0,-23);ctx.lineTo(23,0);ctx.lineTo(0,23);ctx.lineTo(-23,0);ctx.closePath();ctx.fillStyle='#fff';ctx.fill();ctx.lineWidth=7;ctx.strokeStyle='#111827';ctx.stroke();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fillStyle='#111827';ctx.fill();ctx.restore()}
function compass(){if(!bg.complete||!bg.naturalWidth)return;ctx.clearRect(0,0,2500,1500);ctx.drawImage(bg,0,0,2500,1500);if(showPeopleMarkers)P.forEach(p=>{if(!ctl[p].checked)return;PAN.forEach(a=>{const q=pt(a,RAW[p]);dot(q[0],q[1],C[p])});MOR.forEach(a=>{const q=mpt(a,RAW[p]);dot(q[0],q[1],C[p])})});const av=selectedAverage();if(ctl.average.checked&&av){PAN.forEach(a=>{const q=pt(a,av);avg(q[0],q[1])});MOR.forEach(a=>{const q=mpt(a,av);avg(q[0],q[1])})}}
bg.onload=compass;bg.src='https://10groups.github.io/compassimage.png';
const GROUPS=[
 ['General',[['x','General alignment','Generally Left','Generally Right'],['y','Authority','Generally Libertarian','Generally Authoritarian']]],['Economy',[['ax','Economic system','Socialism','Capitalism'],['ay','Market regulation','Laissez-Faire','Regulated']]],['Government',[['bx','Power structure','Autocracy','Democracy'],['by','State authority','Libertarian','Authoritarian']]],['Diplomacy',[['cx','Scope','Universal','Particular'],['cy','International outlook','Globalism','Nationalism']]],['Society',[['dx','Social direction','Progress','Tradition'],['dy','Change posture','Reform','Conserve']]],['Culture',[['gx','Social structure','Equality','Hierarchy'],['gy','Cultural model','Multiculturalism','Monoculturalism']]],['Technology',[['ex','Technological pace','Acceleration','Deceleration'],['ey','Technology ideal','Primitivism','Transhumanism']]],['Law',[['fx','Legal tradition','Common Law','Civil Law'],['fy','Justice model','Rehabilitation','Punishment']]],['Procedure',[['hx','Political persistence','Compromise','Persist'],['hy','Method','Direct','Transitional']]],['Politics',[['ix','Political intensity','Moderate','Radical'],['iy','Political engagement','Apolitical','Politicized']]],['Morality',[['ja','Social ethic','Collectivism','Individualism'],['jb','Change ethic','Revolution','Peaceful'],['jc','Philosophical style','Idealism','Realism'],['jd','Moral framework','Consequential','Deontological']]]
];
const ypos={aiden:9,tommy:19,justin:29,taylor:39};function pct(v){return(Math.max(-10,Math.min(10,v))+10)*5}function signed(v){const x=Math.round(v*100)/100;return Math.abs(x)<.005?'0.00':`${x>0?'+':''}${x.toFixed(2)}`}
const axesRoot=document.getElementById('axesGrid'),summaryRoot=document.getElementById('summaryStrip');
function axes(){GROUPS.forEach(([name,as])=>{const card=document.createElement('section');card.className='axis-group';card.innerHTML=`<h3>${name}</h3>`;as.forEach(([k,label,left,right])=>{const row=document.createElement('div');row.className='axis-row';row.innerHTML=`<div class="axis-title-row"><span class="axis-end">${left}</span><span class="axis-center">${label}</span><span class="axis-end right">${right}</span></div>`;const track=document.createElement('div');track.className='axis-track';P.forEach(p=>{const m=document.createElement('i');m.className='axis-marker';m.dataset.person=p;m.style.left=`${pct(RAW[p][k])}%`;m.style.top=`${ypos[p]}px`;m.style.background=`rgb(${C[p]})`;m.title=`${N[p]}: ${signed(RAW[p][k])}`;track.appendChild(m)});const a=document.createElement('i');a.className='axis-average';a.dataset.axis=k;a.style.top='24px';track.appendChild(a);row.appendChild(track);const f=document.createElement('div');f.className='axis-footer';f.innerHTML=`<span>-10</span><span class="avg" data-average-label="${k}"></span><span>+10</span>`;row.appendChild(f);card.appendChild(row)});axesRoot.appendChild(card)})}
function updateAverageMarkers(){const av=selectedAverage();document.querySelectorAll('.axis-average').forEach(m=>{if(!av||!ctl.average.checked){m.classList.add('hidden-marker');return}const k=m.dataset.axis;m.classList.remove('hidden-marker');m.style.left=`${pct(av[k])}%`;m.title=`Selected average: ${signed(av[k])}`});document.querySelectorAll('[data-average-label]').forEach(label=>{const k=label.dataset.averageLabel;label.textContent=av?`Selected average ${signed(av[k])}`:'No people selected'})}
function summary(){summaryRoot.innerHTML='';const av=selectedAverage(),selected=selectedPeople();const who=selected.length?selected.map(p=>N[p]).join(' + '):'None';const cards=av?[[`Selected people`,who],['General',`x ${signed(av.x)}, y ${signed(av.y)}`],['Economy',`x ${signed(av.ax)}, y ${signed(av.ay)}`],['Government',`x ${signed(av.bx)}, y ${signed(av.by)}`],['Diplomacy',`x ${signed(av.cx)}, y ${signed(av.cy)}`],['Society',`x ${signed(av.dx)}, y ${signed(av.dy)}`],['Culture',`x ${signed(av.gx)}, y ${signed(av.gy)}`]]:[['Selected people','None'],['Average','Select at least one person']];cards.forEach(([a,b])=>{const d=document.createElement('div');d.className='summary-card';d.innerHTML=`<b>${a}</b><span>${b}</span>`;summaryRoot.appendChild(d)})}
function sync(){document.querySelectorAll('.axis-marker').forEach(m=>m.classList.toggle('hidden-marker',!showPeopleMarkers||!ctl[m.dataset.person].checked));updateAverageMarkers();summary();compass()}
P.forEach(p=>ctl[p].addEventListener('change',sync));ctl.average.addEventListener('change',sync);
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const m=b.dataset.preset;if(m==='all'){P.forEach(p=>ctl[p].checked=true);ctl.average.checked=true;showPeopleMarkers=true}else if(m==='people'){P.forEach(p=>ctl[p].checked=true);ctl.average.checked=false;showPeopleMarkers=true}else{P.forEach(p=>ctl[p].checked=true);ctl.average.checked=true;showPeopleMarkers=false}sync()});
axes();sync();
