const STORAGE_KEY='rip.toolbox.time.v1';
export const defaultState=()=>({version:1,format24:false,referenceId:'home',offsetHours:0,clocks:[{id:'home',name:'Home',zone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'},{id:'london',name:'London',zone:'Europe/London'},{id:'tokyo',name:'Tokyo',zone:'Asia/Tokyo'}]});
export function validZone(zone){try{new Intl.DateTimeFormat('en-US',{timeZone:zone}).format();return true}catch{return false}}
export function zoneParts(date,zone,format24=false){if(!validZone(zone))throw new Error(`Unsupported time zone: ${zone}`);const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:zone,year:'numeric',month:'short',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:!format24,timeZoneName:'shortOffset'}).formatToParts(date).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));return parts}
export function calendarKey(date,zone){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));return `${p.year}-${p.month}-${p.day}`}
export function dayDifference(date,zone,referenceZone){const a=Date.parse(calendarKey(date,zone)+'T00:00:00Z');const b=Date.parse(calendarKey(date,referenceZone)+'T00:00:00Z');return Math.round((a-b)/86400000)}
export function serializeState(state){return JSON.stringify(state)}
export function deserializeState(raw){try{const parsed=JSON.parse(raw);if(!parsed||!Array.isArray(parsed.clocks)||!parsed.clocks.length)return defaultState();const clocks=parsed.clocks.filter(c=>c&&c.id&&c.name&&validZone(c.zone)).slice(0,16);if(!clocks.length)return defaultState();return{version:1,format24:Boolean(parsed.format24),referenceId:clocks.some(c=>c.id===parsed.referenceId)?parsed.referenceId:clocks[0].id,offsetHours:Number.isFinite(+parsed.offsetHours)?Math.max(-168,Math.min(168,+parsed.offsetHours)):0,clocks}}catch{return defaultState()}}
export function loadState(){try{return deserializeState(localStorage.getItem(STORAGE_KEY))}catch{return defaultState()}}
export function saveState(state){try{localStorage.setItem(STORAGE_KEY,serializeState(state));return true}catch{return false}}
export function shiftedNow(offsetHours){return new Date(Date.now()+offsetHours*3600000)}
export function uid(){return globalThis.crypto?.randomUUID?.()||`clock-${Date.now()}-${Math.random().toString(36).slice(2)}`}
export const commonZones=['UTC','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','America/Phoenix','America/Anchorage','Pacific/Honolulu','America/Toronto','America/Vancouver','America/Mexico_City','America/Sao_Paulo','Europe/London','Europe/Dublin','Europe/Paris','Europe/Berlin','Europe/Rome','Europe/Madrid','Europe/Warsaw','Europe/Athens','Africa/Cairo','Africa/Johannesburg','Asia/Jerusalem','Asia/Dubai','Asia/Kolkata','Asia/Bangkok','Asia/Singapore','Asia/Hong_Kong','Asia/Shanghai','Asia/Tokyo','Asia/Seoul','Australia/Perth','Australia/Adelaide','Australia/Sydney','Pacific/Auckland'];